import SingleCourse from "@/Components/FreeCoursesComponent/SingleCourse";
import bannerImg from "@/Assets/Images/digital_ocean_serias.webp"

export default function CoursesHub()
{
  return(
      <div>
        {/* Free Courses */}
          <div className={"pt-5 lg:pt-10"}>

              <h1 className={"mb-10 lg:mb-16 text-center font-bold underline underline-offset-8 text-primary-dark text-4xl md:text-5xl lg:text-6xl"}> Our Free Courses </h1>

              <div className={"mx-auto w-fit grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 md:gap-x-9 lg:gap-x-32 gap-y-20 mb-20"}>

                  <SingleCourse bannerImg={bannerImg} bannerTittle={"Digital Ocean Series: Deployment on Cloud"} bannerDesc={"This course is focused on providing hands-on experience with deploying applications on DigitalOcean's cloud platform using Droplets. Students will learn how to create and configure Droplets, connect to them via SSH, and use popular tools such as Git, Nginx, and Node.js to deploy web applications. The course will also cover best practices for securing and managing Droplets, as well as scaling and monitoring applications. By the end of the course, students will have the skills and knowledge necessary to deploy and manage their own applications on DigitalOcean's platform."}/>
                  <SingleCourse bannerImg={bannerImg} bannerTittle={"Digital Ocean Series: Deployment on Cloud"} bannerDesc={"This course is focused on providing hands-on experience with deploying applications on DigitalOcean's cloud platform using Droplets. Students will learn how to create and configure Droplets, connect to them via SSH, and use popular tools such as Git, Nginx, and Node.js to deploy web applications. The course will also cover best practices for securing and managing Droplets, as well as scaling and monitoring applications. By the end of the course, students will have the skills and knowledge necessary to deploy and manage their own applications on DigitalOcean's platform."}/>
                  <SingleCourse bannerImg={bannerImg} bannerTittle={"Digital Ocean Series: Deployment on Cloud"} bannerDesc={"This course is focused on providing hands-on experience with deploying applications on DigitalOcean's cloud platform using Droplets. Students will learn how to create and configure Droplets, connect to them via SSH, and use popular tools such as Git, Nginx, and Node.js to deploy web applications. The course will also cover best practices for securing and managing Droplets, as well as scaling and monitoring applications. By the end of the course, students will have the skills and knowledge necessary to deploy and manage their own applications on DigitalOcean's platform."}/>
                  <SingleCourse bannerImg={bannerImg} bannerTittle={"Digital Ocean Series: Deployment on Cloud"} bannerDesc={"This course is focused on providing hands-on experience with deploying applications on DigitalOcean's cloud platform using Droplets. Students will learn how to create and configure Droplets, connect to them via SSH, and use popular tools such as Git, Nginx, and Node.js to deploy web applications. The course will also cover best practices for securing and managing Droplets, as well as scaling and monitoring applications. By the end of the course, students will have the skills and knowledge necessary to deploy and manage their own applications on DigitalOcean's platform."}/>
                  <SingleCourse bannerImg={bannerImg} bannerTittle={"Digital Ocean Series: Deployment on Cloud"} bannerDesc={"This course is focused on providing hands-on experience with deploying applications on DigitalOcean's cloud platform using Droplets. Students will learn how to create and configure Droplets, connect to them via SSH, and use popular tools such as Git, Nginx, and Node.js to deploy web applications. The course will also cover best practices for securing and managing Droplets, as well as scaling and monitoring applications. By the end of the course, students will have the skills and knowledge necessary to deploy and manage their own applications on DigitalOcean's platform."}/>
                  <SingleCourse bannerImg={bannerImg} bannerTittle={"Digital Ocean Series: Deployment on Cloud"} bannerDesc={"This course is focused on providing hands-on experience with deploying applications on DigitalOcean's cloud platform using Droplets. Students will learn how to create and configure Droplets, connect to them via SSH, and use popular tools such as Git, Nginx, and Node.js to deploy web applications. The course will also cover best practices for securing and managing Droplets, as well as scaling and monitoring applications. By the end of the course, students will have the skills and knowledge necessary to deploy and manage their own applications on DigitalOcean's platform."}/>
                  <SingleCourse bannerImg={bannerImg} bannerTittle={"Digital Ocean Series: Deployment on Cloud"} bannerDesc={"This course is focused on providing hands-on experience with deploying applications on DigitalOcean's cloud platform using Droplets. Students will learn how to create and configure Droplets, connect to them via SSH, and use popular tools such as Git, Nginx, and Node.js to deploy web applications. The course will also cover best practices for securing and managing Droplets, as well as scaling and monitoring applications. By the end of the course, students will have the skills and knowledge necessary to deploy and manage their own applications on DigitalOcean's platform."}/>
                  <SingleCourse bannerImg={bannerImg} bannerTittle={"Digital Ocean Series: Deployment on Cloud"} bannerDesc={"This course is focused on providing hands-on experience with deploying applications on DigitalOcean's cloud platform using Droplets. Students will learn how to create and configure Droplets, connect to them via SSH, and use popular tools such as Git, Nginx, and Node.js to deploy web applications. The course will also cover best practices for securing and managing Droplets, as well as scaling and monitoring applications. By the end of the course, students will have the skills and knowledge necessary to deploy and manage their own applications on DigitalOcean's platform."}/>
                  <SingleCourse bannerImg={bannerImg} bannerTittle={"Digital Ocean Series: Deployment on Cloud"} bannerDesc={"This course is focused on providing hands-on experience with deploying applications on DigitalOcean's cloud platform using Droplets. Students will learn how to create and configure Droplets, connect to them via SSH, and use popular tools such as Git, Nginx, and Node.js to deploy web applications. The course will also cover best practices for securing and managing Droplets, as well as scaling and monitoring applications. By the end of the course, students will have the skills and knowledge necessary to deploy and manage their own applications on DigitalOcean's platform."}/>
                  <SingleCourse bannerImg={bannerImg} bannerTittle={"Digital Ocean Series: Deployment on Cloud"} bannerDesc={"This course is focused on providing hands-on experience with deploying applications on DigitalOcean's cloud platform using Droplets. Students will learn how to create and configure Droplets, connect to them via SSH, and use popular tools such as Git, Nginx, and Node.js to deploy web applications. The course will also cover best practices for securing and managing Droplets, as well as scaling and monitoring applications. By the end of the course, students will have the skills and knowledge necessary to deploy and manage their own applications on DigitalOcean's platform."}/>
                  <SingleCourse bannerImg={bannerImg} bannerTittle={"Digital Ocean Series: Deployment on Cloud"} bannerDesc={"This course is focused on providing hands-on experience with deploying applications on DigitalOcean's cloud platform using Droplets. Students will learn how to create and configure Droplets, connect to them via SSH, and use popular tools such as Git, Nginx, and Node.js to deploy web applications. The course will also cover best practices for securing and managing Droplets, as well as scaling and monitoring applications. By the end of the course, students will have the skills and knowledge necessary to deploy and manage their own applications on DigitalOcean's platform."}/>
                  <SingleCourse bannerImg={bannerImg} bannerTittle={"Digital Ocean Series: Deployment on Cloud"} bannerDesc={"This course is focused on providing hands-on experience with deploying applications on DigitalOcean's cloud platform using Droplets. Students will learn how to create and configure Droplets, connect to them via SSH, and use popular tools such as Git, Nginx, and Node.js to deploy web applications. The course will also cover best practices for securing and managing Droplets, as well as scaling and monitoring applications. By the end of the course, students will have the skills and knowledge necessary to deploy and manage their own applications on DigitalOcean's platform."}/>
                  <SingleCourse bannerImg={bannerImg} bannerTittle={"Digital Ocean Series: Deployment on Cloud"} bannerDesc={"This course is focused on providing hands-on experience with deploying applications on DigitalOcean's cloud platform using Droplets. Students will learn how to create and configure Droplets, connect to them via SSH, and use popular tools such as Git, Nginx, and Node.js to deploy web applications. The course will also cover best practices for securing and managing Droplets, as well as scaling and monitoring applications. By the end of the course, students will have the skills and knowledge necessary to deploy and manage their own applications on DigitalOcean's platform."}/>
                  <SingleCourse bannerImg={bannerImg} bannerTittle={"Digital Ocean Series: Deployment on Cloud"} bannerDesc={"This course is focused on providing hands-on experience with deploying applications on DigitalOcean's cloud platform using Droplets. Students will learn how to create and configure Droplets, connect to them via SSH, and use popular tools such as Git, Nginx, and Node.js to deploy web applications. The course will also cover best practices for securing and managing Droplets, as well as scaling and monitoring applications. By the end of the course, students will have the skills and knowledge necessary to deploy and manage their own applications on DigitalOcean's platform."}/>


              </div>

          </div>
      </div>
  );
}